# -*- coding: utf-8 -*-
# Deployment settings for Foodwar.
# This file is autogenerated by the mkb system and used by the s3e deployment
# tool during the build process.

config = {}
cmdline = ['E:/Program Files (x86)/Marmelade/8.1/s3e/makefile_builder/mkb.py', 'e:/Documents/GitHub/Marmalade Projects/Foodwar/Foodwar.mkb', '--deploy-only', '--hub-data', 'E:/Documents/GitHub/Marmalade Projects/Foodwar/project_Foodwar/mkb-wp81.txt', '--buildenv=VC14', '--buildenv-toolset=WP81']
mkb = 'e:/Documents/GitHub/Marmalade Projects/Foodwar/Foodwar.mkb'
mkf = ['e:\\program files (x86)\\marmelade\\8.1\\s3e\\s3e-default.mkf', 'e:\\program files (x86)\\marmelade\\8.1\\extensions\\s3eamazonads\\s3eamazonads.mkf', 'e:\\program files (x86)\\marmelade\\8.1\\modules\\iwutil\\iwutil.mkf', 'e:\\program files (x86)\\marmelade\\8.1\\modules\\third_party\\libjpeg\\libjpeg.mkf', 'e:\\program files (x86)\\marmelade\\8.1\\modules\\third_party\\libpng\\libpng.mkf', 'e:\\program files (x86)\\marmelade\\8.1\\modules\\third_party\\zlib\\zlib.mkf', 'e:\\program files (x86)\\marmelade\\8.1\\platform_libs\\android\\amazon-ads-android-sdk\\amazon-ads-android-sdk.mkf', 'e:\\program files (x86)\\marmelade\\8.1\\platform_libs\\iphone\\amazon-ads-ios-sdk\\amazon-ads-ios-sdk.mkf']

class DeployConfig(object):
    pass

######### ASSET GROUPS #############

assets = {}

assets['Default'] = [
    ('e:/Documents/GitHub/Marmalade Projects/Foodwar\data', '.', 0),
]

######### DEFAULT CONFIG #############

class DefaultConfig(DeployConfig):
    embed_icf = -1
    name = 'Foodwar'
    pub_sign_key = 0
    priv_sign_key = 0
    caption = 'Foodwar'
    long_caption = 'Foodwar'
    version = [0, 0, 1]
    config = ['e:/Documents/GitHub/Marmalade Projects/Foodwar/data/app.icf']
    data_dir = 'e:/Documents/GitHub/Marmalade Projects/Foodwar/data'
    mkb_dir = 'e:/Documents/GitHub/Marmalade Projects/Foodwar'
    iphone_link_lib = ['s3eAmazonAds']
    osx_ext_dll = []
    wp81_extra_pri = []
    ws8_ext_capabilities = []
    ws8_ext_native_only_dll = []
    win10_ext_uap_capabilities = []
    win10_ext_native_dll = []
    ws81_ext_native_only_dll = []
    android_external_res = []
    win32_ext_dll = []
    wp8_ext_capabilities = []
    ws8_extra_res = []
    iphone_extra_plugins = []
    ws81_ext_managed_dll = []
    iphone_link_libdir = ['e:/program files (x86)/marmelade/8.1/extensions/s3eamazonads/lib/iphone']
    android_extra_application_manifest = ['e:/program files (x86)/marmelade/8.1/extensions/s3eamazonads/source/android/ExtraAppManifests.xml']
    win10_extra_res = []
    ws8_ext_native_dll = []
    android_external_assets = []
    blackberry_extra_descriptor = []
    android_ext_target_sdk_version = [17]
    android_extra_manifest = []
    wp81_ext_sdk_ref = []
    iphone_link_libdirs = []
    wp81_ext_device_capabilities = []
    win10_ext_capabilities = []
    linux_ext_lib = []
    android_ext_min_sdk_version = [4]
    wp81_ext_native_only_dll = []
    ws8_ext_managed_dll = []
    ws8_ext_sdk_manifest_part = []
    ws8_ext_device_capabilities = []
    ws81_extra_pri = []
    android_external_jars = ['e:/program files (x86)/marmelade/8.1/platform_libs/android/amazon-ads-android-sdk/third_party/lib/amazon-ads-5.5.149.jar', 'e:/program files (x86)/marmelade/8.1/extensions/s3eamazonads/lib/android/s3eAmazonAds.jar']
    win8_winrt_extra_res = []
    wp81_ext_sdk_manifest_part = []
    wp81_extra_res = []
    wp81_ext_managed_dll = []
    wp81_ext_capabilities = []
    win10_ext_managed_dll = []
    iphone_extra_plist = ['e:/program files (x86)/marmelade/8.1/extensions/s3eamazonads/s3eAmazonAds.plist']
    ws81_ext_sdk_manifest_part = []
    ws81_ext_device_capabilities = []
    android_supports_gl_texture = []
    ws8_ext_sdk_ref = []
    iphone_extra_string = []
    tizen_so = []
    wp8_ext_native_dll = []
    win10_ext_sdk_manifest_part = []
    win10_extra_pri = []
    win10_ext_device_capabilities = []
    win8_phone_extra_res = []
    win8_store_extra_res = []
    win32_aux_dll = []
    ws81_ext_sdk_ref = []
    iphone_link_opts = ['-Fe:/program files (x86)/marmelade/8.1/platform_libs/iphone/amazon-ads-ios-sdk/third_party/Ads -framework AmazonAd', '-weak_framework AdSupport -weak_framework CoreLocation -weak_framework SystemConfiguration', '-weak_framework CoreTelephony -weak_framework MediaPlayer', '-weak_framework EventKit -weak_framework EventKitUI']
    wp8_extra_res = []
    ws81_ext_native_dll = []
    ws8_extra_pri = []
    wp8_ext_managed_dll = []
    android_extra_packages = []
    android_so = ['e:/program files (x86)/marmelade/8.1/extensions/s3eamazonads/lib/android/libs3eAmazonAds.so']
    wp8_ext_sdk_ref = []
    osx_extra_res = []
    ws81_extra_res = []
    wp81_ext_native_dll = []
    ws81_ext_capabilities = []
    iphone_link_libs = []
    android_extra_strings = []
    target = {
         'wp81-arm' : {
                   'debug'   : r'e:/Documents/GitHub/Marmalade Projects/Foodwar/build_foodwar_vc14_wp81toolset/Debug_Foodwar_VC14_WP81TOOLSET_arm/Foodwar.s86',
                   'release' : r'e:/Documents/GitHub/Marmalade Projects/Foodwar/build_foodwar_vc14_wp81toolset/Release_Foodwar_VC14_WP81TOOLSET_arm/Foodwar.s86',
                 },
         'wp81-x86' : {
                   'debug'   : r'e:/Documents/GitHub/Marmalade Projects/Foodwar/build_foodwar_vc14_wp81toolset/Debug_Foodwar_VC14_WP81TOOLSET_x86/Foodwar.s86',
                   'release' : r'e:/Documents/GitHub/Marmalade Projects/Foodwar/build_foodwar_vc14_wp81toolset/Release_Foodwar_VC14_WP81TOOLSET_x86/Foodwar.s86',
                 },
        }
    arm_arch = ''
    assets_original = assets
    assets = assets['Default']

default = DefaultConfig()
